### ISSUE TITLE
Missing plt.show()

### ISSUE THREAD

**Issue by awickert** [UMN-Hydro/SecondCreek_TempModel#1]
Rainvsheadplots.py

Plots aren't plotting when just run from a terminal

**Comment by jacktlange** [comment]
Ahh, i have been runnig the script in the spyder interface. I'll fix the
issue in the morning.

**Comment by awickert** [comment]
That's what I figured -- I'll watch the issue for when you close it.

**Comment by jacktlange** [comment]
Issue is resolved
